# name: Run Telegram Bot

# on:
#   push:
#     branches:
#       - main
#   schedule:
#     - cron: '*/15 * * * *' # Runs every 15 minutes

# jobs:
#   run-bot:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.x'  # Ensure this matches the Python version your code supports

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pyrogram TgCrypto

#       - name: Run bot
#         env:
#           TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
#         run: |
#           python Telebot.py
